apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-service
spec:
  replicas: {{ .Values.trackingService.replicas }}
  selector:
    matchLabels:
      app: tracking-service
  template:
    metadata:
      labels:
        app: tracking-service
    spec:
      containers:
        - name: tracking-service
          image: {{ .Values.trackingService.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.trackingService.port }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.trackingService.port }}
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.trackingService.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: tracking-service
spec:
  selector:
    app: tracking-service
  ports:
    - port: {{ .Values.trackingService.port }}
      targetPort: {{ .Values.trackingService.port }}
  type: NodePort