server:
  port: 8083
  tomcat:
    accesslog:
      enabled: true
      directory: /app/logs
      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  application:
    name: assignment-service
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  metrics:
    export:
      otlp:
        enabled: false