server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order_service_db
    username: swiggy_user
    password: swiggy_pass123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
assignment-service:
  base-url: http://localhost:8083

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true