server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      directory: /app/logs
      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/order_service_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

assignment-service:
  base-url: http://localhost:8083

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger:4318/v1/traces
  metrics:
    export:
      otlp:
        enabled: false