name: Build and Deploy Swiggy System

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        service: [order-service, catalog-service, assignment-service, tracking-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version tag
        id: version
        shell: powershell
        run: echo "TAG=v${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Build ${{ matrix.service }} image
        run: docker build --no-cache -f ${{ github.workspace }}/${{ matrix.service }}/Dockerfile -t ${{ matrix.service }}:${{ steps.version.outputs.TAG }} ${{ github.workspace }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version tag
        id: version
        shell: powershell
        run: echo "TAG=v${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Update values.yaml with new tags
        shell: powershell
        run: |
          (Get-Content ${{ github.workspace }}/swiggy-chart/values.yaml) -replace 'order-service:.*', 'order-service:${{ steps.version.outputs.TAG }}' | Set-Content ${{ github.workspace }}/swiggy-chart/values.yaml
          (Get-Content ${{ github.workspace }}/swiggy-chart/values.yaml) -replace 'catalog-service:.*', 'catalog-service:${{ steps.version.outputs.TAG }}' | Set-Content ${{ github.workspace }}/swiggy-chart/values.yaml
          (Get-Content ${{ github.workspace }}/swiggy-chart/values.yaml) -replace 'assignment-service:.*', 'assignment-service:${{ steps.version.outputs.TAG }}' | Set-Content ${{ github.workspace }}/swiggy-chart/values.yaml
          (Get-Content ${{ github.workspace }}/swiggy-chart/values.yaml) -replace 'tracking-service:.*', 'tracking-service:${{ steps.version.outputs.TAG }}' | Set-Content ${{ github.workspace }}/swiggy-chart/values.yaml

      - name: Deploy via Helm
        run: helm upgrade swiggy ${{ github.workspace }}/swiggy-chart

      - name: Verify rollout - catalog-service
        run: kubectl rollout status deployment/catalog-service --timeout=180s

      - name: Verify rollout - assignment-service
        run: kubectl rollout status deployment/assignment-service --timeout=180s

      - name: Verify rollout - tracking-service
        run: kubectl rollout status deployment/tracking-service --timeout=180s

      - name: Verify rollout - order-service (Argo Rollout)
        run: kubectl get rollout order-service