name: Build and Deploy Swiggy System

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version tag
        id: version
        shell: powershell
        run: echo "TAG=v${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Build order-service image
        run: docker build --no-cache -f swiggy-system/order-service/Dockerfile -t order-service:${{ steps.version.outputs.TAG }} swiggy-system/

      - name: Build catalog-service image
        run: docker build --no-cache -f swiggy-system/catalog-service/Dockerfile -t catalog-service:${{ steps.version.outputs.TAG }} swiggy-system/

      - name: Build assignment-service image
        run: docker build --no-cache -f swiggy-system/assignment-service/Dockerfile -t assignment-service:${{ steps.version.outputs.TAG }} swiggy-system/

      - name: Build tracking-service image
        run: docker build --no-cache -f swiggy-system/tracking-service/Dockerfile -t tracking-service:${{ steps.version.outputs.TAG }} swiggy-system/

      - name: Update values.yaml with new tags
        shell: powershell
        run: |
          (Get-Content swiggy-system/swiggy-chart/values.yaml) -replace 'order-service:.*', 'order-service:${{ steps.version.outputs.TAG }}' | Set-Content swiggy-system/swiggy-chart/values.yaml
          (Get-Content swiggy-system/swiggy-chart/values.yaml) -replace 'catalog-service:.*', 'catalog-service:${{ steps.version.outputs.TAG }}' | Set-Content swiggy-system/swiggy-chart/values.yaml
          (Get-Content swiggy-system/swiggy-chart/values.yaml) -replace 'assignment-service:.*', 'assignment-service:${{ steps.version.outputs.TAG }}' | Set-Content swiggy-system/swiggy-chart/values.yaml
          (Get-Content swiggy-system/swiggy-chart/values.yaml) -replace 'tracking-service:.*', 'tracking-service:${{ steps.version.outputs.TAG }}' | Set-Content swiggy-system/swiggy-chart/values.yaml

      - name: Deploy via Helm
        run: helm upgrade swiggy ./swiggy-system/swiggy-chart

      - name: Verify rollout - catalog-service
        run: kubectl rollout status deployment/catalog-service --timeout=120s

      - name: Verify rollout - assignment-service
        run: kubectl rollout status deployment/assignment-service --timeout=120s

      - name: Verify rollout - tracking-service
        run: kubectl rollout status deployment/tracking-service --timeout=120s

      - name: Verify rollout - order-service (Argo Rollout)
        run: kubectl argo rollouts status order-service --timeout=180s